version: '3.3'

services:
  mongo_db_nest:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - /home/gerardo/Desktop/PLATZI/docker_volumes/mongo_data:/data/db
